### ISSUE TITLE
When you fix it?

### ISSUE THREAD

**Issue by nonamich** [shinntype/bellefair#11]
So can no longer continue.
https://i.imgur.com/UOCkElC.jpg

**Comment by nickshinn** [comment]
Sorry, but Bellefair only has one weight, Regular.
Fake Bold does not work.

**Comment by nonamich** [comment]
in the previous version it was good

**Comment by nickshinn** [comment]
I only worked on the original version, I don't know what has happened to Bellefair since then, to cause this effect.

**Comment by nonamich** [comment]
The font is beautiful. Thank you for that. It is a pity that I can not use it.
